blank_issues_enabled: true
contact_links:
  - name: Online Documentation
    url: https://github.com/ptheywood/issue-template-testing/wiki
    about: Please see the online documentation
  - name: Discussions Board / Support
    url: https://github.com/ptheywood/issue-template-testing
    about: Please ask and answer questions here.
  - name: Documentation Issues
    url: https://github.com/ptheywood/issue-template-testing/issues
    about: Please report issues with the documentation here
  - name: Website Issues
    url: https://github.com/ptheywood/issue-template-testing/issues
    about: Please report issues with the website here